name: GhostSCP
author: Команда DX Foundation
version: 3.0.0
description: Добавляет призрачных SCP в комплекс
halloween-theme: true
organization: DX Foundation

# 🎃 DX FOUNDATION PLUGIN
# Организация: DX Foundation
# Хэллоуинская версия 3.0.0
